---
- name: Add required databases
  mysql_db:
    encoding: "utf8"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ item }}"
    state: absent
  loop:
    - "{{ containers.bookstack.subdomain }}"
    - "{{ containers.grafana.subdomain }}"
    - "{{ containers.nextcloud.subdomain }}"
    - "{{ containers.promgen.subdomain }}"
    - "{{ containers.statping.subdomain.0 }}"
  no_log: true # Don't log output to Ansible logs, due to sensitive data

- name: Add Bookstack user
  mysql_user:
    host: "{{ containers.bookstack.subdomain }}.{{ containers.bookstack.network }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.bookstack.subdomain }}"
    password: "{{ mariadb.bookstack_passwd }}"
    priv: "{{ containers.bookstack.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

- name: Add Grafana user
  mysql_user:
    host: "{{ containers.grafana.subdomain }}.{{ containers.grafana.network }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.grafana.subdomain }}"
    password: "{{ mariadb.grafana_passwd }}"
    priv: "{{ containers.grafana.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

- name: Add Nextcloud user
  mysql_user:
    host: "{{ containers.nextcloud.subdomain }}.{{ containers.nextcloud.network }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.nextcloud.subdomain }}"
    password: "{{ mariadb.nextcloud_passwd }}"
    priv: "{{ containers.nextcloud.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

- name: Add Promgen user
  mysql_user:
    host: "{{ containers.promgen.subdomain }}.{{ containers.promgen.network }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.promgen.subdomain }}"
    password: "{{ mariadb.promgen_passwd }}"
    priv: "{{ containers.promgen.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

- name: Add Statping user
  mysql_user:
    host: "{{ containers.statping.subdomain.0 }}.{{ containers.statping.network }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.statping.subdomain.0 }}"
    password: "{{ mariadb.statping_passwd }}"
    priv: "{{ containers.statping.subdomain.0 }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data
...
