---
# Database Creation
- name: add required databases
  mysql_db:
    encoding: "utf8"
    login_host: "172.18.0.8"
    # login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ item }}"
    state: absent
  loop:
    # - "{{ containers.bookstack.subdomain }}"
    # - "{{ containers.grafana.subdomain }}"
    # - "{{ containers.nextcloud.subdomain }}"
    # - "{{ containers.promgen.subdomain }}"
    # - "{{ containers.statping.subdomain.0 }}"
  no_log: true # Don't log output to Ansible logs, due to sensitive data

# Bookstack User
- name: add bookstack user
  mysql_user:
    host: "{{ containers.bookstack.subdomain }}.{{ networks.docker.primary.name }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.bookstack.subdomain }}"
    password: "{{ mariadb.bookstack_passwd }}"
    priv: "{{ containers.bookstack.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

# Cloudbeaver User
- name: add cloudbeaver user
  mysql_user:
    host: "{{ containers.cloudbeaver.subdomain }}.{{ networks.docker.primary.name }}"
    login_host: "172.18.0.8"
    # login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.cloudbeaver.subdomain }}"
    password: "{{ mariadb.cloudbeaver_passwd }}"
    priv: "*.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

# Grafana User
- name: add grafana user
  mysql_user:
    host: "{{ containers.grafana.subdomain }}.{{ networks.docker.primary.name }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.grafana.subdomain }}"
    password: "{{ mariadb.grafana_passwd }}"
    priv: "{{ containers.grafana.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

# NextCloud User
- name: add nextcloud user
  mysql_user:
    host: "{{ containers.nextcloud.subdomain }}.{{ networks.docker.primary.name }}"
    login_host: "{{ containers.mariadb.subdomain }}"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.nextcloud.subdomain }}"
    password: "{{ mariadb.nextcloud_passwd }}"
    priv: "{{ containers.nextcloud.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

# PromGen User
- name: add promgen user
  mysql_user:
    host: "{{ containers.promgen.subdomain }}.{{ networks.docker.primary.name }}"
    login_host: "172.18.0.8"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.promgen.subdomain }}"
    password: "{{ mariadb.promgen_passwd }}"
    priv: "{{ containers.promgen.subdomain }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data

# StatPing User
- name: add statping user
  mysql_user:
    host: "{{ containers.statping.subdomain.0 }}.{{ networks.docker.primary.name }}"
    login_host: "172.18.0.8"
    login_password: "{{ mariadb.mariadb_passwd }}"
    login_port: "{{ mariadb.login_port }}"
    login_user: "{{ mariadb.login_user }}"
    name: "{{ containers.statping.subdomain.0 }}"
    password: "{{ mariadb.statping_passwd }}"
    priv: "{{ containers.statping.subdomain.0 }}.*:ALL"
    state: present
  no_log: true # Don't log output to Ansible logs, due to sensitive data
...
