---
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.bookstack.subdomain }}"
    solo: "true"
    state: "present"
    type: "CNAME"
    value: "{{ containers.traefik.subdomain }}.{{ domain }}"
    zone: "{{ domain }}"

- name: Verify required directories with correct permissions are created
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.bookstack.subdomain }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

- name: Start Bookstack
  docker_container:
    name: "{{ containers.bookstack.subdomain }}"
    hostname: "{{ containers.bookstack.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: linuxserver/bookstack
    links: # Prevent container creation and startup until linked containers are running
      - "{{ containers.mariadb.subdomain }}:{{ containers.mariadb.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.bookstack.subdomain }}:/config:z"
    env:
      DB_HOST: "{{ containers.mariadb.subdomain }}:{{ containers.mariadb.port }}" # MariaDB Host
      DB_USER: "{{ containers.bookstack.subdomain }}" # MariaDB User
      DB_PASS: "{{ mariadb.bookstack_passwd }}" # MariaDB Password
      DB_DATABASE: "{{ containers.bookstack.subdomain }}" # Bookstack Database
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      TZ: "{{ timezone }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ containers.bookstack.network }}"
        aliases: "{{ containers.bookstack.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.bookstack-rtr.entrypoints: "https"
      traefik.http.routers.bookstack-rtr.rule: "Host(`{{ containers.bookstack.subdomain }}.{{ containers.bookstack.tld }}`)"
      traefik.http.routers.bookstack-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.bookstack-rtr.service: "bookstack-svc"
      traefik.http.services.bookstack-svc.loadbalancer.server.port: "{{ containers.bookstack.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.bookstack-rtr.middlewares: "chain-no-auth@file"
...
