---
  # DNS Record Creation for hostname of container
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns: 
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.mylar.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address }}' }

  # Verify required directories with correct permissions are created
- name: check dir ownership
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.mylar.subdomain }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

  # Standup the container in inventory
- name: Start Mylar
  docker_container:
    name: "{{ containers.mylar.subdomain }}"
    hostname: "{{ containers.mylar.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: linuxserver/mylar
    links: # Prevent container creation and startup until linked containers are running 
    - "{{ containers.nzbget.subdomain }}:{{ containers.nzbget.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    # Mount required directories with the container
    mounts: 
      - type: bind 
        source: "{{ directories.container_root }}/{{ containers.mylar.subdomain }}"
        target: "{{ directories.config_dir }}"
      - type: volume # Mount shared data volume
        source: "{{ directories.data_vol }}"
        target: /mnt
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.mylar.subdomain }}"
    purge_networks: yes
    pull: true 
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.mylar-rtr.entrypoints: "https"
      traefik.http.routers.mylar-rtr.rule: "Host(`{{ containers.mylar.subdomain }}.{{ containers.mylar.tld }}`)"
      traefik.http.routers.mylar-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.mylar-rtr.service: "mylar-svc"
      traefik.http.services.mylar-svc.loadbalancer.server.port: "{{ containers.mylar.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.mylar-rtr.middlewares: "chain-oauth@file"
...
