---
- name: Start Docker-GC
  docker_container:
    name: "{{ containers.gc.subdomain }}"
    hostname: "{{ containers.gc.subdomain }}"
    state: started
    privileged: yes
    restart_policy: unless-stopped
    image: spotify/docker-gc
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "/var/run/docker.sock:/var/run/docker.sock:z"
      - "/etc:/etc:ro"
    env:
      REMOVE_VOLUMES: "1" # Should GC Remove abandoned volumes?
      TZ: "{{ timezone }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ containers.gc.network }}"
        aliases: "{{ containers.gc.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
...
