---
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.tdarr.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}' }

- name: Verify required directories with correct permissions are created
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.tdarr.subdomain }}/mongodb"
    state: directory
    setype: container_file_t
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"

- name: Start Tdarr
  docker_container:
    name: "{{ containers.tdarr.subdomain }}"
    hostname: "{{ containers.tdarr.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: haveagitgat/tdarr
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.tdarr.subdomain }}:/home/Tdarr/Documents/Tdarr:z"
      - "{{ directories.container_root }}/{{ containers.tdarr.subdomain }}/mongodb:/var/lib/mongodb:z"
      - "{{ directories.host_drive_root }}:{{ directories.drive_root }}:rshared"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      TZ: "{{ timezone }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ containers.tdarr.network }}"
        aliases: "{{ containers.tdarr.subdomain }}"
    purge_networks: yes
    pull: true 
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.tdarr-rtr.entrypoints: "https"
      traefik.http.routers.tdarr-rtr.rule: "Host(`{{ containers.tdarr.subdomain }}.{{ containers.tdarr.tld }}`)"
      traefik.http.routers.tdarr-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.tdarr-rtr.service: "tdarr-svc"
      traefik.http.services.tdarr-svc.loadbalancer.server.port: "{{ containers.tdarr.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.tdarr-rtr.middlewares: "chain-oauth@file"
...
