---
- name: Verify required directories with correct permissions are created
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ item }}"
    state: directory
    setype: container_file_t
  loop:
    - "{{ containers.fail2ban.subdomain }}/action.d"
    - "{{ containers.fail2ban.subdomain }}/filter.d"
    - "{{ containers.fail2ban.subdomain }}/jail.d"

- name: Verify templated required files with correct permissions are created
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ directories.container_root }}/{{ containers.fail2ban.subdomain }}/{{ item }}"
    mode: 0640
  loop:
    - "filter.d/traefik-404.local"
    - "filter.d/traefik-badbots.local"
    - "filter.d/traefik-botsearch.local"
    - "jail.d/default.local"
    - "jail.d/recidive.local"
    - "jail.d/sshd.local"
    - "jail.d/traefik.local"

- name: Start Fail2ban
  docker_container:
    name: "{{ containers.fail2ban.subdomain }}"
    hostname: "{{ containers.fail2ban.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: crazymax/fail2ban
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.fail2ban.subdomain }}:/data:z"
      - "/var/log:/var/log:ro"
    env:
      F2B_DB_PURGE_AGE: "7d" # Age at which bans should be purged from the database (default 1d)
      F2B_IPTABLES_CHAIN: "INPUT" # Specifies the iptables chain to which the Fail2Ban rules should be added (default DOCKER-USER)
      F2B_LOG_LEVEL: "INFO" # Log level output (default INFO)
      F2B_LOG_TARGET: "STDOUT" # Set the log target. This could be a file, SYSLOG, STDERR or STDOUT (default STDOUT)
      TZ: "{{ timezone }}" # The timezone assigned to the container (default UTC)
    capabilities: 
      - NET_ADMIN
      - NET_RAW
    networks_cli_compatible: no
    network_mode: host
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
...
