---
  # Verify required directories with correct permissions are created
- name: check dir ownership
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.influxdb.subdomain }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

  # Standup the container in inventory
- name: Start InfluxDB
  docker_container:
    name: "{{ containers.influxdb.subdomain }}"
    hostname: "{{ containers.influxdb.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: influxdb
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    # Mount required directories with the container
    mounts: 
      - type: bind 
        source: "{{ directories.container_root }}/{{ containers.influxdb.subdomain }}"
        target: /var/lib/influxdb
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      # INFLUXDB_DB: ""
      # INFLUXDB_HTTP_AUTH_ENABLED: true
      # INFLUXDB_ADMIN_USER: ""
      # INFLUXDB_ADMIN_PASSWORD: ""
      # INFLUXDB_USER: ""
      # INFLUXDB_USER_PASSWORD: ""
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.influxdb.subdomain }}"
    purge_networks: yes
    pull: true 
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
...
