---
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.plex.subdomain.0 }}" # Plex Server Subdomain
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address }}' }

- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.plex.subdomain.1 }}" # Plex WebTools Subdomain
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address }}' }

- name: Verify required directories with correct permissions are created
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.plex.subdomain.0 }}/"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

- name: Check if GPU exists on host to pass to Plex
  stat:
    path: '/dev/dri'
  register: dev_dri

  # Standup the container in inventory
- name: Start Plex
  docker_container:
    name: "{{ containers.plex.subdomain.0 }}"
    hostname: "{{ containers.plex.subdomain.0 }}"
    state: started
    restart_policy: unless-stopped
    image: plexinc/pms-docker
    links: # Prevent container creation and startup until linked containers are running
      - "{{ containers.rclone.subdomain }}:{{ containers.rclone.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.plex.subdomain.0 }}:/config:z"
      - "{{ directories.host_drive_root }}:{{ directories.drive_root }}:shared"
    env:
      PLEX_UID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PLEX_GID: "{{ users.primary.gid }}" # Pass proper GID to the container
      UMASK: "{{ mount_options.umask }}" # File UMASK
      TZ: "{{ timezone }}"
    devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(False) else omit }}" # Pass GPU to the container, if it exists
    etc_hosts: # Block Plex Spying
      { 'analytics.plex.tv': '127.0.0.1', 'metrics.plex.tv': '127.0.0.1' }
    ports: # Pass required Plex ports to the host interface
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.plex.subdomain.0 }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.plex-rtr.entrypoints: "https"
      traefik.http.routers.plex-rtr.rule: "Host(`{{ containers.plex.subdomain.0 }}.{{ containers.plex.tld }}`)"
      traefik.http.routers.plex-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.plex-rtr.service: "plex-svc"
      traefik.http.services.plex-svc.loadbalancer.server.port: "{{ containers.plex.port.0 | default('80') }}"
      ## Middlewares
      traefik.http.routers.plex-rtr.middlewares: "chain-no-auth@file"
      ## HTTP Routers
      traefik.http.routers.plex-tools-rtr.entrypoints: "https"
      traefik.http.routers.plex-tools-rtr.rule: "Host(`{{ containers.plex.subdomain.1 }}.{{ containers.plex.tld }}`)"
      traefik.http.routers.plex-tools-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.plex-tools-rtr.service: "plex-tools-svc"
      traefik.http.services.plex-tools-svc.loadbalancer.server.port: "{{ containers.plex.port.1 | default('80') }}"
      ## Middlewares
      traefik.http.routers.plex-tools-rtr.middlewares: "chain-oauth@file"
...
