---
  # DNS Record Creation for hostname of container
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.readarr.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.record }}"
    value: "{{ item.proto }}"
    zone: "{{ domain }}"
  loop:
    - { record: 'A', proto: '{{ ansible_default_ipv4.address }}' }
    - { record: 'AAAA', proto: '{{ ansible_default_ipv6.address }}' }

  # Verify required directories with correct permissions are created
- name: check dir ownership
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.readarr.subdomain }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

  # Standup the container in inventory
- name: Start Readarr
  docker_container:
    name: "{{ containers.readarr.subdomain }}"
    hostname: "{{ containers.readarr.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: hotio/readarr:unstable
    links: # Prevent container creation and startup until linked containers are running
    - "{{ containers.nzbget.subdomain }}:{{ containers.nzbget.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    # Mount required directories with the container
    volumes:
      - "{{ directories.container_root }}/{{ containers.readarr.subdomain }}:/config/app:z"
      - "{{ directories.host_data_dir }}:{{ directories.data_dir }}:z"
    env:
      DEBUG: "yes"
      PUID: "{{ users.primary.uid }}"
      PGID: "{{ users.primary.gid }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.readarr.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.readarr-rtr.entrypoints: "https"
      traefik.http.routers.readarr-rtr.rule: "Host(`{{ containers.readarr.subdomain }}.{{ containers.readarr.tld }}`)"
      traefik.http.routers.readarr-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.readarr-rtr.service: "readarr-svc"
      traefik.http.services.readarr-svc.loadbalancer.server.port: "{{ containers.readarr.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.readarr-rtr.middlewares: "chain-oauth@file"
...
