---
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.tautulli.subdomain }}"
    solo: "true"
    state: "present"
    type: "CNAME"
    value: "{{ containers.traefik.subdomain }}.{{ domain }}"
    zone: "{{ domain }}"

- name: Verify required directories with correct permissions are created
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.tautulli.subdomain }}/scripts"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

- name: Verify required files with correct permissions are created
  copy:
    src: "{{ item }}"
    dest: "{{ directories.container_root }}/{{ containers.tautulli.subdomain }}/scripts/{{ item }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    mode: 0770
  loop:
    - "99-requests.sh"
    - "kill_stream.py"

- name: Start Tautulli
  docker_container:
    name: "{{ containers.tautulli.subdomain }}"
    hostname: "{{ containers.tautulli.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: linuxserver/tautulli
    links: # Prevent container creation and startup until linked containers are running
    - "{{ containers.plex.subdomain.0 }}:{{ containers.plex.subdomain.0 }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.tautulli.subdomain }}:/config:z"
      - "{{ directories.container_root }}/{{ containers.tautulli.subdomain }}/scripts/99-requests.sh:/etc/cont-init.d/99-requests.sh:z"
      - "{{ directories.container_root }}/{{ containers.plex.subdomain.0 }}/Library/Application Support/Plex Media Server/Logs:/logs:ro" # Mount Plex Server logs
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      TZ: "{{ timezone }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ containers.tautulli.network }}"
        aliases: "{{ containers.tautulli.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.tautulli-rtr.entrypoints: "https"
      traefik.http.routers.tautulli-rtr.rule: "Host(`{{ containers.tautulli.subdomain }}.{{ containers.tautulli.tld }}`)"
      traefik.http.routers.tautulli-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.tautulli-rtr.service: "tautulli-svc"
      traefik.http.services.tautulli-svc.loadbalancer.server.port: "{{ containers.tautulli.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.tautulli-rtr.middlewares: "chain-oauth@file"
...
