---
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.nextcloud.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address }}' }

- name: Verify required directories with correct permissions are created
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ item }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t
  loop:
    - "{{ containers.nextcloud.subdomain }}"

- name: Verify templated required files with correct permissions are created
  template:
    src: "templates/config.php.j2"
    dest: "{{ directories.container_root }}/{{ containers.nextcloud.subdomain }}/www/nextcloud/config/config.php"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    mode: 0640

- name: Start NextCloud
  docker_container:
    name: "{{ containers.nextcloud.subdomain }}"
    hostname: "{{ containers.nextcloud.subdomain }}.{{ containers.nextcloud.tld }}"
    state: started
    restart_policy: unless-stopped
    image: linuxserver/nextcloud
    links: # Prevent container creation and startup until linked containers are running
      - "{{ containers.mariadb.subdomain }}:{{ containers.mariadb.subdomain }}"
      - "{{ containers.rclone.subdomain }}:{{ containers.rclone.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.nextcloud.subdomain }}:/config:z"
      - "{{ directories.host_data_dir }}:{{ directories.data_dir }}:shared"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      TZ: "{{ timezone }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.nextcloud.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.nextcloud-rtr.entrypoints: "https"
      traefik.http.routers.nextcloud-rtr.rule: "Host(`{{ containers.nextcloud.subdomain }}.{{ containers.nextcloud.tld }}`)"
      traefik.http.routers.nextcloud-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.nextcloud-rtr.service: "nextcloud-svc"
      traefik.http.services.nextcloud-svc.loadbalancer.server.port: "{{ containers.nextcloud.port | default('80') }}"
      traefik.http.services.nextcloud-svc.loadbalancer.server.scheme: "{{ containers.nextcloud.proto }}"
      ## Middlewares
      traefik.http.routers.nextcloud-rtr.middlewares: "chain-no-auth@file"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.permanent: "true"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.regex: "https://(.*)/.well-known/(card|cal)dav"
      traefik.http.middlewares.nextcloud-redirectregex.redirectRegex.replacement: "https://${1}/remote.php/dav/"
...
