---
  # DNS Record Creation for hostname of container
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.jellyfin.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address }}' }

  # Verify required directories with correct permissions are created
- name: check dir ownership
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.jellyfin.subdomain }}/"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

  # Check if GPU exists on host to pass to Plex Container
- name: Check /dev/dri exists
  stat:
    path: '/dev/dri'
  register: dev_dri

# Standup the container in inventory
- name: Start Jellyfin
  docker_container:
    name: "{{ containers.jellyfin.subdomain }}"
    hostname: "{{ containers.jellyfin.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: linuxserver/jellyfin
    links: # Prevent container creation and startup until linked containers are running
      - "{{ containers.rclone.subdomain }}:{{ containers.rclone.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    # Mount required directories with the container
    volumes:
      - "{{ directories.container_root }}/{{ containers.jellyfin.subdomain }}:/config:z"
      - "{{ directories.host_drive_root }}:{{ directories.drive_root }}:sharedz"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      UMASK: "{{ mount_options.umask }}" # File UMASK
    devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(False) else omit }}" # Pass GPU to the container, if it exists
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.jellyfin.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.jellyfin-rtr.entrypoints: "https"
      traefik.http.routers.jellyfin-rtr.rule: "Host(`{{ containers.jellyfin.subdomain }}.{{ containers.jellyfin.tld }}`)"
      traefik.http.routers.jellyfin-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.jellyfin-rtr.service: "jellyfin-svc"
      traefik.http.services.jellyfin-svc.loadbalancer.server.port: "{{ containers.jellyfin.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.jellyfin-rtr.middlewares: "chain-no-auth@file"
...
