---
# DNS Record Creation for hostname of container
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns: 
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.portainer.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address }}' }
    
  # Verify required directories with correct permissions are created
- name: check dir ownership
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.portainer.subdomain }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

  # Standup the container in inventory
- name: Start Portainer
  docker_container:
    name: "{{ containers.portainer.subdomain }}"
    hostname: "{{ containers.portainer.subdomain }}"
    state: started
    privileged: yes
    restart_policy: unless-stopped
    image: portainer/portainer
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    # Mount required directories with the container
    mounts: 
      - type: bind 
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind 
        source: "{{ directories.container_root }}/{{ containers.portainer.subdomain }}"
        target: "{{ directories.data_dir }}"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.portainer.subdomain }}"
    purge_networks: yes
    pull: true 
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.portainer-rtr.entrypoints: "https"
      traefik.http.routers.portainer-rtr.rule: "Host(`{{ containers.portainer.subdomain }}.{{ containers.portainer.tld }}`)"
      traefik.http.routers.portainer-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.portainer-rtr.service: "portainer-svc"
      traefik.http.services.portainer-svc.loadbalancer.server.port: "{{ containers.portainer.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.portainer-rtr.middlewares: "chain-oauth@file"
...
