---
  # DNS Record Creation for hostname of container
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns: 
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.sonarr.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.record }}"
    value: "{{ item.proto }}"
    zone: "{{ domain }}"
  loop:
    - { record: 'A', proto: '{{ ansible_default_ipv4.address }}' }
    - { record: 'AAAA', proto: '{{ ansible_default_ipv6.address }}' }

  # Verify required directories with correct permissions are created
- name: check dir ownership
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.sonarr.subdomain }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

  # Verify templated required files with correct permissions are created
- name: Adding Required Files
  template:
    src: "templates/config.xml.j2"
    dest: "{{ directories.container_root }}/{{ containers.sonarr.subdomain }}/config.xml"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    mode: 0660

  # Standup the container in inventory
- name: Start Sonarr
  docker_container:
    name: "{{ containers.sonarr.subdomain }}"
    hostname: "{{ containers.sonarr.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: linuxserver/sonarr
    links: # Prevent container creation and startup until linked containers are running 
    - "{{ containers.nzbget.subdomain }}:{{ containers.nzbget.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
      # Mount required directories with the container
    mounts: 
      - type: bind 
        source: "{{ directories.container_root }}/{{ containers.sonarr.subdomain }}"
        target: "{{ directories.config_dir }}"
      - type: bind
        source: "{{ directories.data_dir }}"
        target: "{{ directories.data_dir }}"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.sonarr.subdomain }}"
    purge_networks: yes
    pull: true 
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.sonarr-rtr.entrypoints: "https"
      traefik.http.routers.sonarr-rtr.rule: "Host(`{{ containers.sonarr.subdomain }}.{{ containers.sonarr.tld }}`)"
      traefik.http.routers.sonarr-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.sonarr-rtr.service: "sonarr-svc"
      traefik.http.services.sonarr-svc.loadbalancer.server.port: "{{ containers.sonarr.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.sonarr-rtr.middlewares: "chain-oauth@file"
...
