---
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.alltube.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}' }

- name: Verify required directories with correct permissions are created
  file:
    recurse: yes
    path: "{{ directories.container_root }}/{{ containers.alltube.subdomain }}"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    state: directory
    setype: container_file_t

- name: Verify templated required files with correct permissions are created
  template:
    src: "templates/config.yml.j2"
    dest: "{{ directories.container_root }}/{{ containers.alltube.subdomain }}/config.yml"
    owner: "{{ users.primary.user }}"
    group: "{{ users.primary.group }}"
    mode: 0660

- name: Start Alltube
  docker_container:
    name: "{{ containers.alltube.subdomain }}"
    hostname: "{{ containers.alltube.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: rudloff/alltube
    links: # Prevent container creation and startup until linked containers are running
      - "{{ containers.rclone.subdomain }}:{{ containers.rclone.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.alltube.subdomain }}/config.yml:/config/config.yml:z"
      - "{{ directories.host_data_dir }}:{{ directories.data_dir }}:rshared"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      UMASK: "{{ mount_options.umask }}" # File UMASK
      TZ: "{{ timezone }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ containers.alltube.network }}"
        aliases: "{{ containers.alltube.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.alltube-rtr.entrypoints: "https"
      traefik.http.routers.alltube-rtr.rule: "Host(`{{ containers.alltube.subdomain }}.{{ containers.alltube.tld }}`)"
      traefik.http.routers.alltube-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.alltube-rtr.service: "alltube-svc"
      traefik.http.services.alltube-svc.loadbalancer.server.port: "{{ containers.alltube.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.alltube-rtr.middlewares: "chain-oauth@file"
...
