---
- name: Start Syncarr Radarr
  docker_container:
    name: "{{ containers.syncarr_radarr.subdomain }}"
    hostname: "{{ containers.syncarr_radarr.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: syncarr/syncarr:latest
    links: # Prevent container creation and startup until linked containers are running 
    - "{{ containers.radarr.subdomain }}:{{ containers.radarr.subdomain }}"
    - "{{ containers.radarr4k.subdomain }}:{{ containers.radarr4k.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      RADARR_A_URL: "http://{{ containers.radarr.subdomain }}:{{ containers.radarr.port }}" # Normal Radarr host
      RADARR_A_KEY: "{{ api_keys.radarr }}" # Normal Radarr API key
      RADARR_A_PROFILE: "Any" # Normal Radarr profile
      RADARR_A_PATH: "{{ directories.drive_root }}/{{ directories.movies }}" # Normal Radarr path
      RADARR_B_URL: "http://{{ containers.radarr4k.subdomain }}:{{ containers.radarr4k.port }}" # 4K Radarr host
      RADARR_B_KEY: "{{ api_keys.radarr4k }}" # 4K Radarr API key
      RADARR_B_PROFILE: "Ultra-HD" # 4K Radarr profile
      RADARR_B_PATH: "{{ directories.drive_root }}/{{ directories.movies_4k }}" # 4K Radarr path
      SYNC_INTERVAL_SECONDS:  "86400" # How often to perform the sync
      SYNCARR_BIDIRECTIONAL_SYNC: "1" # Should Syncarr sync between both servers?
      SYNCARR_AUTO_SEARCH: "1" # Should Syncarr search on add?
      SYNCARR_MONITOR_NEW_CONTENT: "1" # Should new content be monitored?
    networks_cli_compatible: no
    networks:
      - name: "{{ networks.docker.primary.name }}"
        aliases: "{{ containers.syncarr_radarr.subdomain }}"
    purge_networks: yes
    pull: true 
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
...
