---
- name: Create DNS Reconds on Cloudflare for this container
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    proxied: "yes"
    record: "{{ containers.nzbget.subdomain }}"
    solo: "true"
    state: "present"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    zone: "{{ domain }}"
  loop:
    - { type: 'A', value: '{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}' }
    - { type: 'AAAA', value: '{{ ansible_default_ipv6.address|default(ansible_all_ipv6_addresses[0]) }}' }

- name: Verify required directories with correct permissions are created
  file:
    group: "{{ users.primary.group }}"
    owner: "{{ users.primary.user }}"
    path: "{{ directories.container_root }}/{{ item }}"
    recurse: yes
    setype: container_file_t
    state: directory
  loop:
    - "{{ containers.nzbget.subdomain }}/cont-init.d"
    - "{{ containers.nzbget.subdomain }}/installer"
    - "{{ containers.nzbget.subdomain }}/nzbs"
    - "{{ containers.nzbget.subdomain }}/scripts"
    - "{{ containers.nzbget.subdomain }}/services.d"

- name: Verify templated required files with correct permissions are created
  template:
    dest: "{{ directories.container_root }}/{{ containers.nzbget.subdomain }}/{{ item }}"
    group: "{{ users.primary.group }}"
    mode: 0770
    owner: "{{ users.primary.user }}"
    src: "templates/{{ item }}.j2"
  loop:
    - "cont-init.d/30-config"
    - "installer/installer.sh"
    - "nzbget.conf"
    - "scripts/Completion.py"
    - "services.d/run"

- name: Start NZBGet
  docker_container:
    name: "{{ containers.nzbget.subdomain }}"
    hostname: "{{ containers.nzbget.subdomain }}"
    state: started
    restart_policy: unless-stopped
    image: linuxserver/nzbget
    links: # Prevent container creation and startup until linked containers are running
      - "{{ containers.rclone.subdomain }}:{{ containers.rclone.subdomain }}"
    log_driver: "json-file"
    log_options:
      max-size: "12m"
      max-file: "3"
    volumes: # Mount required directories with the container
      - "{{ directories.container_root }}/{{ containers.nzbget.subdomain }}:/config:z"
      - "{{ directories.container_root }}/{{ containers.nzbget.subdomain }}/cont-init.d/30-config:/etc/cont-init.d/30-config:z"
      - "{{ directories.host_data_dir }}:{{ directories.data_dir }}:rshared"
    env:
      PUID: "{{ users.primary.uid }}" # Pass proper UID to the container
      PGID: "{{ users.primary.gid }}" # Pass proper GID to the container
      UMASK: "{{ mount_options.umask }}" # File UMASK
      TZ: "{{ timezone }}"
    networks_cli_compatible: no
    networks:
      - name: "{{ containers.nzbget.network }}"
        aliases: "{{ containers.nzbget.subdomain }}"
    purge_networks: yes
    pull: true
    labels:
      ## Watchtower Updates
      com.centurylinklabs.watchtower.enable: "true"
      ## Enable Traefik
      traefik.enable: "true"
      ## HTTP Routers
      traefik.http.routers.nzbget-rtr.entrypoints: "https"
      traefik.http.routers.nzbget-rtr.rule: "Host(`{{ containers.nzbget.subdomain }}.{{ containers.nzbget.tld }}`)"
      traefik.http.routers.nzbget-rtr.tls: "true"
      ## HTTP Services
      traefik.http.routers.nzbget-rtr.service: "nzbget-svc"
      traefik.http.services.nzbget-svc.loadbalancer.server.port: "{{ containers.nzbget.port | default('80') }}"
      ## Middlewares
      traefik.http.routers.nzbget-rtr.middlewares: "chain-oauth@file"
...
